-- IRATestData.lua
-- 불뱀/폭요(TBC 2.0/2.1) 레이드 데이터 스냅샷. 테스트모드 버튼이 이걸 로드해서 ledger에 박음.
-- 시작골드 / 머니 변동은 박지 않음. 블랙리스트(켈타스 P4 무기/황천의 쐐기 더미 등)는 제외.
local _, ADDONSELF = ...

ADDONSELF.testData = {
    label = "불뱀/폭요(TBC 2.0/2.1) 레이드 데이터",
    count = 80,
    entries = {
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 30447,
            item           = "|cffa335ee|Hitem:30447::::::::70::::::::::|h[불타는 구원의 고서]|h|r",
        },
        {
            beneficiary    = "황당기사욜라쎄다",
            saleState      = "confirmed",
            cost           = 2200,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "황당기사욜라쎄다",
            count          = 1,
            reliableItemID = 29925,
            item           = "|cffa335ee|Hitem:29925::::::::70::::::::::|h[불사조날개 망토]|h|r",
        },
        {
            beneficiary    = "애플레인",
            saleState      = "confirmed",
            cost           = 1500,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "애플레인",
            count          = 1,
            reliableItemID = 32944,
            item           = "|cffa335ee|Hitem:32944::::::::70::::::::::|h[불사조의 갈퀴발톱]|h|r",
        },
        {
            beneficiary    = "핸섬맨",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "핸섬맨",
            count          = 1,
            reliableItemID = 29983,
            item           = "|cffa335ee|Hitem:29983::::::::70::::::::::|h[지옥강철 전투투구]|h|r",
        },
        {
            beneficiary    = "나디연",
            saleState      = "confirmed",
            cost           = 2000,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "나디연",
            count          = 1,
            reliableItemID = 30248,
            item           = "|cffa335ee|Hitem:30248::::::::70::::::::::|h[정복당한 용사의 어깨갑옷]|h|r",
        },
        {
            beneficiary    = "세구사랑해",
            saleState      = "confirmed",
            cost           = 2000,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "세구사랑해",
            count          = 1,
            reliableItemID = 30248,
            item           = "|cffa335ee|Hitem:30248::::::::70::::::::::|h[정복당한 용사의 어깨갑옷]|h|r",
        },
        {
            beneficiary    = "문이",
            saleState      = "confirmed",
            cost           = 4100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "문이",
            count          = 1,
            reliableItemID = 30250,
            item           = "|cffa335ee|Hitem:30250::::::::70::::::::::|h[정복당한 영웅의 어깨갑옷]|h|r",
        },
        {
            beneficiary    = "내가그린그림",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "내가그린그림",
            count          = 1,
            reliableItemID = 30020,
            item           = "|cffa335ee|Hitem:30020::::::::70::::::::::|h[마법학자의 화염끈]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 900,
            noBeneficiary  = false,
            looter         = "다른생각제타",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30183,
            item           = "|cffa335ee|Hitem:30183::::::::70::::::::::|h[황천의 소용돌이]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 30449,
            item           = "|cffa335ee|Hitem:30449::::::::70::::::::::|h[공허의 별 부적]|h|r",
        },
        {
            beneficiary    = "핸섬맨",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "핸섬맨",
            count          = 1,
            reliableItemID = 29950,
            item           = "|cffa335ee|Hitem:29950::::::::70::::::::::|h[붉은경비대 경갑]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 29977,
            item           = "|cffa335ee|Hitem:29977::::::::70::::::::::|h[별빛영혼 바지]|h|r",
        },
        {
            beneficiary    = "지온현기",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = true,
            looter         = "술약선",
            winner         = "지온현기",
            count          = 1,
            reliableItemID = 30302,
            item           = "|cffa335ee|Hitem:30302::::::::70::::::::::|h[도안: 깊은 어둠의 허리띠]|h|r",
        },
        {
            beneficiary    = "죽척곰",
            saleState      = "confirmed",
            cost           = 3500,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "죽척곰",
            count          = 1,
            reliableItemID = 29997,
            item           = "|cffa335ee|Hitem:29997::::::::70::::::::::|h[순찰대 사령관의 고리]|h|r",
        },
        {
            beneficiary    = "나는솔로순자",
            saleState      = "confirmed",
            cost           = 3900,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "나는솔로순자",
            count          = 1,
            reliableItemID = 30237,
            item           = "|cffa335ee|Hitem:30237::::::::70::::::::::|h[정복당한 수호자의 가슴보호구]|h|r",
        },
        {
            beneficiary    = "문이",
            saleState      = "confirmed",
            cost           = 4800,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "문이",
            count          = 1,
            reliableItemID = 30238,
            item           = "|cffa335ee|Hitem:30238::::::::70::::::::::|h[정복당한 영웅의 가슴보호구]|h|r",
        },
        {
            beneficiary    = "누옴즌사",
            saleState      = "confirmed",
            cost           = 3900,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "누옴즌사",
            count          = 1,
            reliableItemID = 30237,
            item           = "|cffa335ee|Hitem:30237::::::::70::::::::::|h[정복당한 수호자의 가슴보호구]|h|r",
        },
        {
            beneficiary    = "문이",
            saleState      = "confirmed",
            cost           = 3600,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "문이",
            count          = 1,
            reliableItemID = 32405,
            item           = "|cffa335ee|Hitem:32405::::::::70::::::::::|h[신록의 구슬]|h|r",
        },
        {
            beneficiary    = "슝하고팍하고탁",
            saleState      = "confirmed",
            cost           = 1000,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "슝하고팍하고탁",
            count          = 1,
            reliableItemID = 29987,
            item           = "|cffa335ee|Hitem:29987::::::::70::::::::::|h[태양왕의 건틀릿]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 900,
            noBeneficiary  = false,
            looter         = "다른생각제타",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30183,
            item           = "|cffa335ee|Hitem:30183::::::::70::::::::::|h[황천의 소용돌이]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 900,
            noBeneficiary  = false,
            looter         = "다른생각제타",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30183,
            item           = "|cffa335ee|Hitem:30183::::::::70::::::::::|h[황천의 소용돌이]|h|r",
        },
        {
            beneficiary    = "애플레인",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "애플레인",
            count          = 1,
            reliableItemID = 30054,
            item           = "|cffa335ee|Hitem:30054::::::::70::::::::::|h[순찰대 사령관의 갑옷]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 2500,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30052,
            item           = "|cffa335ee|Hitem:30052::::::::70::::::::::|h[필살의 반지]|h|r",
        },
        {
            beneficiary    = "김쏸무",
            saleState      = "confirmed",
            cost           = 1500,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "김쏸무",
            count          = 1,
            reliableItemID = 30049,
            item           = "|cffa335ee|Hitem:30049::::::::70::::::::::|h[심연의 돌]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 900,
            noBeneficiary  = false,
            looter         = "다른생각제타",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30183,
            item           = "|cffa335ee|Hitem:30183::::::::70::::::::::|h[황천의 소용돌이]|h|r",
        },
        {
            beneficiary    = "울프강",
            saleState      = "confirmed",
            cost           = 2100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "울프강",
            count          = 1,
            reliableItemID = 30057,
            item           = "|cffa335ee|Hitem:30057::::::::70::::::::::|h[박멸의 팔보호구]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 30065,
            item           = "|cffa335ee|Hitem:30065::::::::70::::::::::|h[빛나는 진실의 흉갑]|h|r",
        },
        {
            beneficiary    = "지온현기",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = true,
            looter         = "술약선",
            winner         = "지온현기",
            count          = 1,
            reliableItemID = 30323,
            item           = "|cffa335ee|Hitem:30323::::::::70::::::::::|h[도면: 파수병의 장화]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 1000,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 30067,
            item           = "|cffa335ee|Hitem:30067::::::::70::::::::::|h[수호자의 벨벳 장화]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 22450,
            item           = "|cffa335ee|Hitem:22450::::::::70::::::::::|h[공허의 수정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 22450,
            item           = "|cffa335ee|Hitem:22450::::::::70::::::::::|h[공허의 수정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 22450,
            item           = "|cffa335ee|Hitem:22450::::::::70::::::::::|h[공허의 수정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 22450,
            item           = "|cffa335ee|Hitem:22450::::::::70::::::::::|h[공허의 수정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 22450,
            item           = "|cffa335ee|Hitem:22450::::::::70::::::::::|h[공허의 수정]|h|r",
        },
        {
            beneficiary    = "쪼꼬사탕",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "쪼꼬사탕",
            count          = 1,
            reliableItemID = 30075,
            item           = "|cffa335ee|Hitem:30075::::::::70::::::::::|h[옹이진 고대 흉갑]|h|r",
        },
        {
            beneficiary    = "핸섬맨",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "핸섬맨",
            count          = 1,
            reliableItemID = 30098,
            item           = "|cffa335ee|Hitem:30098::::::::70::::::::::|h[칼날비늘 전투망토]|h|r",
        },
        {
            beneficiary    = "핸섬맨",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = true,
            looter         = "술약선",
            winner         = "핸섬맨",
            count          = 1,
            reliableItemID = 30322,
            item           = "|cffa335ee|Hitem:30322::::::::70::::::::::|h[도면: 전투의 붉은 허리띠]|h|r",
        },
        {
            beneficiary    = "누니와",
            saleState      = "confirmed",
            cost           = 900,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "누니와",
            count          = 1,
            reliableItemID = 30720,
            item           = "|cffa335ee|Hitem:30720::::::::70::::::::::|h[불뱀똬리 매듭]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 900,
            noBeneficiary  = false,
            looter         = "다른생각제타",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30183,
            item           = "|cffa335ee|Hitem:30183::::::::70::::::::::|h[황천의 소용돌이]|h|r",
        },
        {
            beneficiary    = "울프강",
            saleState      = "confirmed",
            cost           = 3100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "울프강",
            count          = 1,
            reliableItemID = 30246,
            item           = "|cffa335ee|Hitem:30246::::::::70::::::::::|h[정복당한 수호자의 다리보호구]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 3900,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30245,
            item           = "|cffa335ee|Hitem:30245::::::::70::::::::::|h[정복당한 용사의 다리보호구]|h|r",
        },
        {
            beneficiary    = "세구사랑해",
            saleState      = "confirmed",
            cost           = 2200,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "세구사랑해",
            count          = 1,
            reliableItemID = 30101,
            item           = "|cffa335ee|Hitem:30101::::::::70::::::::::|h[붉은바다 해적의 조끼]|h|r",
        },
        {
            beneficiary    = "김쏸무",
            saleState      = "confirmed",
            cost           = 2900,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "김쏸무",
            count          = 1,
            reliableItemID = 30247,
            item           = "|cffa335ee|Hitem:30247::::::::70::::::::::|h[정복당한 영웅의 다리보호구]|h|r",
        },
        {
            beneficiary    = "울프강",
            saleState      = "confirmed",
            cost           = 800,
            noBeneficiary  = false,
            looter         = "울프강",
            winner         = "울프강",
            count          = 1,
            reliableItemID = 30183,
            item           = "|cffa335ee|Hitem:30183::::::::70::::::::::|h[황천의 소용돌이]|h|r",
        },
        {
            beneficiary    = "탕탕빵야",
            saleState      = "confirmed",
            cost           = 3100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "탕탕빵야",
            count          = 1,
            reliableItemID = 30241,
            item           = "|cffa335ee|Hitem:30241::::::::70::::::::::|h[정복당한 영웅의 장갑]|h|r",
        },
        {
            beneficiary    = "누니와",
            saleState      = "confirmed",
            cost           = 3100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "누니와",
            count          = 1,
            reliableItemID = 30241,
            item           = "|cffa335ee|Hitem:30241::::::::70::::::::::|h[정복당한 영웅의 장갑]|h|r",
        },
        {
            beneficiary    = "애플레인",
            saleState      = "confirmed",
            cost           = 3100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "애플레인",
            count          = 1,
            reliableItemID = 30241,
            item           = "|cffa335ee|Hitem:30241::::::::70::::::::::|h[정복당한 영웅의 장갑]|h|r",
        },
        {
            beneficiary    = "카구",
            saleState      = "confirmed",
            cost           = 1600,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "카구",
            count          = 1,
            reliableItemID = 30092,
            item           = "|cffa335ee|Hitem:30092::::::::70::::::::::|h[고래가죽 장화]|h|r",
        },
        {
            beneficiary    = "누옴즌사",
            saleState      = "confirmed",
            cost           = 3700,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "누옴즌사",
            count          = 1,
            reliableItemID = 30243,
            item           = "|cffa335ee|Hitem:30243::::::::70::::::::::|h[정복당한 수호자의 투구]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = true,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 30308,
            item           = "|cffa335ee|Hitem:30308::::::::70::::::::::|h[도안: 폭풍우 장화]|h|r",
        },
        {
            beneficiary    = "하이사제",
            saleState      = "confirmed",
            cost           = 4500,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "하이사제",
            count          = 1,
            reliableItemID = 30108,
            item           = "|cffa335ee|Hitem:30108::::::::70::::::::::|h[밝은 심연의 홀]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 3500,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30242,
            item           = "|cffa335ee|Hitem:30242::::::::70::::::::::|h[정복당한 용사의 투구]|h|r",
        },
        {
            beneficiary    = "카구",
            saleState      = "confirmed",
            cost           = 3500,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "카구",
            count          = 1,
            reliableItemID = 30242,
            item           = "|cffa335ee|Hitem:30242::::::::70::::::::::|h[정복당한 용사의 투구]|h|r",
        },
        {
            beneficiary    = "두루루",
            saleState      = "confirmed",
            cost           = 100,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "두루루",
            count          = 1,
            reliableItemID = 30621,
            item           = "|cffa335ee|Hitem:30621::::::::70::::::::::|h[내적인 고요의 프리즘]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 600,
            noBeneficiary  = false,
            looter         = "다른생각제타",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30183,
            item           = "|cffa335ee|Hitem:30183::::::::70::::::::::|h[황천의 소용돌이]|h|r",
        },
        {
            beneficiary    = "다른생각제타",
            saleState      = "confirmed",
            cost           = 600,
            noBeneficiary  = false,
            looter         = "다른생각제타",
            winner         = "다른생각제타",
            count          = 1,
            reliableItemID = 30183,
            item           = "|cffa335ee|Hitem:30183::::::::70::::::::::|h[황천의 소용돌이]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 22450,
            item           = "|cffa335ee|Hitem:22450::::::::70::::::::::|h[공허의 수정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "confirmed",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "술약선",
            count          = 1,
            reliableItemID = 22450,
            item           = "|cffa335ee|Hitem:22450::::::::70::::::::::|h[공허의 수정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22448,
            item           = "|cff0070dd|Hitem:22448::::::::70::::::::::|h[무지갯빛 작은 결정]|h|r",
        },
        {
            beneficiary    = "술약선",
            saleState      = "open",
            cost           = 0,
            noBeneficiary  = false,
            looter         = "술약선",
            winner         = "",
            count          = 1,
            reliableItemID = 22449,
            item           = "|cff0070dd|Hitem:22449::::::::70::::::::::|h[무지갯빛 큰 결정]|h|r",
        },
    },
}
